### ISSUE TITLE
ValueError: None is not a valid WindowState

### ISSUE THREAD

**Issue by chemstar** [coreGreenberet/homematicip-rest-api#117]
Hi,

when calling hmip_cli.py --list-devices i'm getting following error for my devices:

`Traceback (most recent call last):
  File "hmip_cli.py", line 466, in <module>
    main()
  File "hmip_cli.py", line 186, in main
    if not home.get_current_state():
  File "/home/pi/devel/homematic/homematicip-rest-api/homematicip/home.py", line 208, in get_current_state
    self._get_devices(json_state)
  File "/home/pi/devel/homematic/homematicip-rest-api/homematicip/home.py", line 221, in _get_devices
    self.devices.append(self._parse_device(raw))
  File "/home/pi/devel/homematic/homematicip-rest-api/homematicip/home.py", line 227, in _parse_device
    d.from_json(json_state)
  File "/home/pi/devel/homematic/homematicip-rest-api/homematicip/device.py", line 184, in from_json
    self.windowState = WindowState(c["windowState"])
  File "/usr/local/lib/python3.7/enum.py", line 307, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.7/enum.py", line 555, in __new__
    return cls._missing_(value)
  File "/usr/local/lib/python3.7/enum.py", line 568, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: None is not a valid WindowState
`

I think it should regard the HMIP-SWDO sensor.

**Comment by chemstar** [comment]
The next error occurs after update. Don'h have a config.py file inside the directory.

Traceback (most recent call last):
  File "hmip_cli.py", line 466, in <module>
    main()
  File "hmip_cli.py", line 146, in main
    convert_config2ini()
  File "hmip_cli.py", line 31, in convert_config2ini
    import config
  File "/usr/local/lib/python3.7/site-packages/config.py", line 733
    except Exception, e:
                    ^
SyntaxError: invalid syntax
