### ISSUE TITLE
hmip_generate_auth_token.py not working

### ISSUE THREAD

**Issue by NorthyIE** [coreGreenberet/homematicip-rest-api#127]
Hi,
I am trying to authenticate a SilverCrest branded HMIP Access Point, but I get an error trying to generate an access key.
I installed the API by running "pip3 install homematicip" on an up-to-date debian stretch.

When I run "python3 /usr/local/bin/hmip_generate_auth_token.py" I get the following output below.
Any suggestions on what could be wrong?

```
Please enter the accesspoint id (SGTIN): xxxx-xxxx-xxxx-xxxx-xxxx-xxxx
Please enter the client/devicename (leave blank to use default):
Please enter the PIN (leave Blank if there is none):
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 138, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 98, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 88, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 350, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 837, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 281, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 147, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fb3031fae10>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 363, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='srv01.hmip-oem0840.com', port=6969): Max retries exceeded with url: /hmip/auth/connectionRequest (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fb3031fae10>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/hmip_generate_auth_token.py", line 70, in <module>
    main()
  File "/usr/local/bin/hmip_generate_auth_token.py", line 35, in main
    response = auth.connectionRequest(access_point)
  File "/usr/local/lib/python3.5/dist-packages/homematicip/auth.py", line 24, in connectionRequest
    headers=headers)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='srv01.hmip-oem0840.com', port=6969): Max retries exceeded with url: /hmip/auth/connectionRequest (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fb3031fae10>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by NorthyIE** [comment]
I found the issue, there was a webfilter used on our wifi, blocking traffic to port 6969 (labeled as Bittorrent traffic in the filter). Disabling this fixed the error!
