### ISSUE TITLE
invalid syntax error when I try to run "hmip_generate_auth_token"

### ISSUE THREAD

**Issue by Christoph-Caina** [coreGreenberet/homematicip-rest-api#149]
Hi, I need some help running the Script "hmip_generate_auth_token" :-(
As soon as I execute the script, I will get the following error:

```
C:\Users\****\Downloads\homematicip-rest-api-master>python hmip_generate_auth_token.py
Traceback (most recent call last):
  File "hmip_generate_auth_token.py", line 2, in <module>
    import homematicip
  File "C:\Users\****\Downloads\homematicip-rest-api-master\homematicip\__init__.py", line 13
    def find_and_load_config_file() -> HmipConfig:
                                    ^
SyntaxError: invalid syntax
```

I am doing something wrong here?

Thanks a lot,
Christoph

**Comment by Christoph-Caina** [comment]
solved.
I've had Python 2.7 and 3.6 - unfortunately, always the 2.7 version was used to execute the script.
Now it's working as expected.
