### ISSUE TITLE
STRONG_WIND Weather condition

### ISSUE THREAD

**Issue by PalatinCoder** [coreGreenberet/homematicip-rest-api#188]
Hi,
having somewhat extreme weather conditions in Germany right now, I discovered even my Pi doesn't like that:
```
Traceback (most recent call last):
  File "watchdog.py", line 60, in <module>
    home.get_current_state()
  File "/home/pi/.local/lib/python3.5/site-packages/homematicip/home.py", line 255, in get_current_state
    self.from_json(js_home)
  File "/home/pi/.local/lib/python3.5/site-packages/homematicip/home.py", line 195, in from_json
    self.weather.from_json(js_home["weather"])
  File "/home/pi/.local/lib/python3.5/site-packages/homematicip/home.py", line 44, in from_json
    self.weatherCondition = WeatherCondition.from_str(js["weatherCondition"])
  File "/home/pi/.local/lib/python3.5/site-packages/homematicip/base/enums.py", line 29, in from_str
    return cls(text)
  File "/home/pi/.local/lib/python3.5/site-packages/aenum/__init__.py", line 1959, in __call__
    return cls.__new__(cls, value)
  File "/home/pi/.local/lib/python3.5/site-packages/aenum/__init__.py", line 2347, in __new__
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 'STRONG_WIND' is not a valid WeatherCondition
```

**Comment by coreGreenberet** [comment]
yeah they've added strong wind as a new value for the WeatherCondition

**Comment by PalatinCoder** [comment]
Well that was quick! Thank you!
