### ISSUE TITLE
Exception because of the logging handler

### ISSUE THREAD

**Issue by DavidHoffmann** [coreGreenberet/homematicip-rest-api#32]
```
python homematicip_cli.py 
Traceback (most recent call last):
  File "homematicip_cli.py", line 18, in <module>
    logger = create_logger();
  File "homematicip_cli.py", line 13, in create_logger
    handler = logging.handlers.TimedRotatingFileHandler(config.LOGGING_FILENAME, when='midnight', backupCount=5) if config.LOGGING_FILENAME else logging.StreamHandler()
AttributeError: 'module' object has no attribute 'handlers'

```

**Comment by coreGreenberet** [comment]
thanks for the fix
