### ISSUE TITLE
can't generat auth token

### ISSUE THREAD

**Issue by margusveer** [coreGreenberet/homematicip-rest-api#98]
Hi!
Can someone help me in this point ? 

I installed clean hassabian with home assistant 0.69.1 and upgraded and updated today homematicip as well but all same. 

pi@hassbian:~/.local/bin $ python3 hmip_generate_auth_token.py
```
Please enter the accesspoint id (SGTIN): 3014-f711-a000-03d5-699f-xxxx
Traceback (most recent call last):
  File "hmip_generate_auth_token.py", line 70, in <module>
    main()
  File "hmip_generate_auth_token.py", line 20, in main
    home=Home()
  File "/home/pi/.local/lib/python3.5/site-packages/homematicip/home.py", line 127, in __init__
    connection = Connection()
  File "/home/pi/.local/lib/python3.5/site-packages/homematicip/base/base_connection.py", line 44, in __init__
    "language": locale.getdefaultlocale()[0],
  File "/usr/lib/python3.5/locale.py", line 558, in getdefaultlocale
    return _parse_localename(localename)
  File "/usr/lib/python3.5/locale.py", line 486, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8

```

actually whatever I put in SGTIN id - (in xxxx-xxxx-xxxx-xxxx-xxxx-xxxx format) the answer is alway the same.

**Comment by margusveer** [comment]
I do not know exactly what I'm doing, I'm really green with linux and this stuff, but I made ( because this not exciting)  bash_profile file and run's source 
then 
```
pi@hassbian:~ $ source ~/.bash_profile
-bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory

```
then in stackoverflow I find that maybe it's must be in ~/.bashrc
and then some warning: 
```
pi@hassbian:~ $ source ~/.bashrc 
-bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
-bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

```

but after that I run again 

> pi@hassbian:~/.local/bin $ python3 hmip_generate_auth_token.py

and I get my token  - now I try to get it work ;)

**Comment by margusveer** [comment]
yess my devices is appeared on Home Assistant UI ;) - now I try how it's works
